"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = "$all"

command_timeout = 1000

[character]
success_symbol = "🤙"
error_symbol = "🤨"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[golang]
symbol = " "

[directory]
fish_style_pwd_dir_length=1
